

spring:
  jackson:
    # snake case style for response json
    default-property-inclusion: NON_NULL
    property-naming-strategy: SNAKE_CASE
    serialization:
      write-dates-as-timestamps: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://114.212.99.186:5432/l23o6
    username: postgres
    password: 211250076

  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update

  application:
    name: user-service

eureka:
  client:
    service-url:
      defaultZone: http://114.212.100.250:30002/eureka/

sa-token:
#   token-name: token
#   # 30 days
#   timeout: 2592000
#   # no expiration
#   activity-timeout: -1
#   # multi login
#   is-concurrent: true
#   is-share: true
  token-style: uuid
  is-log: true
